---

version: '3'

networks:
  elk:

volumes:
  elasticsearch:

services:
  logspout:
    depends_on:
      - logstash  
    image: gliderlabs/logspout:v3.2.6
    restart: always
    command: 'syslog://logstash:5000'
    environment:
      - EXCLUDE_LABEL=logspout-exclude
    labels:
      logspout-exclude: true
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    networks:
      - elk

  logstash:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/logstash/logstash:6.4.3
    restart: always
    labels:
      logspout-exclude: true
    volumes:
      - ./logstash/:/usr/share/logstash/pipeline/
    networks:
      - elk

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    labels:
      logspout-exclude: true
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      - elk

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:6.4.3
    labels:
      logspout-exclude: true
    ports:
      - 5601:5601
    networks:
      - elk
