---

version: '3'

networks:
  redis:
  mysql:

services:
  redis:
    image: redis:5.0.0-alpine3.8
    restart: always
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "ping"]
      interval: 5s
      timeout: 5s
    networks:
      - redis

  mysql:
    image: mysql:8.0.13
    restart: always
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d:ro
      - ./mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/:ro
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=employees
      - MYSQL_USER=application_user
      - MYSQL_PASS=application_pass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
    networks:
      - mysql

  