---

# Maximum number of jobs to run concurrently
gitlab_runner_concurrent: '{{ ansible_processor_cores }}'

# GitLab coordinator URL
gitlab_runner_coordinator_url: 'https://gitlab.com/ci'
# GitLab registration token
gitlab_runner_registration_token: ''
# Runner description
gitlab_runner_description: '{{ ansible_hostname }}'
# Runner executor
gitlab_runner_executor: 'docker+machine'
# Default Docker image
gitlab_runner_docker_image: 'gitlab/gitlab-runner:alpine-v11.4.2'
# Runner tags
gitlab_runner_tags: ['docker']